name: Upload Pkg
on:
  release:
    types:
      - created
jobs:
  upload_pkg:
    name: Upload Publishable Pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: the_pkg/
      - uses: benc-uk/workflow-dispatch@v1
        with:
          repo: harrysolovay/nothing_to_see_here_either
          workflow: publish.yml
          token: ${{ secrets.GITHUB_TOKEN }}